1-Ada-Lovelace
Sotonka/todo_list pull request #1
Opened 2023-06-10 13:26 UTC by Sotonka

2023-06-14 03:38 UTC, Sotonka commented
скрины и apk в readme

2023-06-18 21:34 UTC, shodafl commented on lib/presentation/widgets/todo_tile.dart
> +      background: Container(
Хотелось бы декомпозировать верстку

2023-06-18 21:34 UTC, shodafl commented on lib/presentation/widgets/todo_tile.dart
> +      secondaryBackground: Container(
Хотелось бы декомпозировать верстку

2023-06-18 21:34 UTC, shodafl commented on lib/presentation/widgets/todo_tile.dart
> +      child: ConstrainedBox(
Можно сделать поаккуратнее и декомпозировать на отдельные виджеты

2023-06-18 21:34 UTC, shodafl commented on lib/presentation/screens/todo_screen.dart
> +          SliverAppBar(
Предлагаю декомпозировать верстку экрана на отдельные виджеты

2023-06-18 21:56 UTC, shodafl requested changes

2023-06-18 21:56 UTC, shodafl commented on lib/app.dart
> +      title: 'Todos',
UI правки:

1. Иконка приложения не по гайдлайнам (отступы и не должно быть прозрачного фона)
2. Не правильный формат даты дед-лайна на списке дел
3. Не правильный цвет StatusBar'a
4. Не правильный цвет плейсхолдера на пикере "важность"
5. Проверить тень у AppBar
6. Разделитель на экране "Создание туду" между дедлайном и кнопкой удалить не по дизайну

2023-06-18 21:56 UTC, shodafl commented on lib/data/repository/todos_repository_impl.dart
> +      return Left(DataFailure());
Возвращаем DataFailure, а как понять какая именно проблема произошла у пользователя?

2023-06-22 06:45 UTC, closed without merging